/* eslint-disable import/no-anonymous-default-export */
export default [
  {
    id: 1,
    title: "Terminator",
    isLike: false,
    genre: "action",
    stock: 6,
    rate: 2.5,
  },
  {
    id: 2,
    title: "Die Hard",
    isLike: false,
    genre: "action",
    stock: 5,
    rate: 2.5,
  },
  {
    id: 3,
    title: "Get Out",
    isLike: true,
    genre: "thriller",
    stock: 6,
    rate: 3.5,
  },
  {
    id: 4,
    title: "Trip to Italy",
    isLike: false,
    genre: "comedy",
    stock: 8,
    rate: 3.5,
  },
  {
    id: 5,
    title: "Airplane",
    isLike: false,
    genre: "comedy",
    stock: 7,
    rate: 3.5,
  },
  {
    id: 6,
    title: "Mortal",
    isLike: false,
    genre: "thriller",
    stock: 7,
    rate: 4.5,
  },
  {
    id: 7,
    title: "Kong vs Go",
    isLike: false,
    genre: "action",
    stock: 8,
    rate: 4.5,
  },
  {
    id: 8,
    title: "Forsaj 9",
    isLike: false,
    genre: "thriller",
    stock: 6,
    rate: 5.5,
  },
  {
    id: 9,
    title: "Anabel season 3",
    isLike: true,
    genre: "comedy",
    stock: 5,
    rate: 3.5,
  },
];
